name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up database
      run: RAILS_ENV=test bundle exec rails db:setup
    - name: Ruby Tests
      run: bundle exec rails test
    - name: System Tests
      run: bundle exec rails test:system
    - name: RuboCop
      run: bundle exec rubocop
    - name: Archive system test artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshots
        path: test/dummy/tmp/screenshots
